Checks: [
  -*,
  bugprone-*,
  performance-*,
  portability-*,
  cppcoreguidelines-*,
  misc-*,

  # Remove
  -bugprone-easily-swappable-parameters,
  -bugprone-macro-parentheses,
  -bugprone-narrowing-conversions,
  -bugprone-reserved-identifier,
  -bugprone-signed-char-misuse,
  -cppcoreguidelines-avoid-c-arrays,
  -cppcoreguidelines-avoid-const-or-ref-data-members,
  -cppcoreguidelines-avoid-do-while,
  -cppcoreguidelines-avoid-magic-numbers,
  -cppcoreguidelines-macro-to-enum,
  -cppcoreguidelines-macro-usage,
  -cppcoreguidelines-missing-std-forward,
  -cppcoreguidelines-narrowing-conversions,
  -cppcoreguidelines-non-private-member-variables-in-classes,
  -cppcoreguidelines-owning-memory,
  -cppcoreguidelines-pro-bounds-array-to-pointer-decay,
  -cppcoreguidelines-pro-bounds-avoid-unchecked-container-access,
  -cppcoreguidelines-pro-bounds-constant-array-index,
  -cppcoreguidelines-pro-bounds-pointer-arithmetic,
  -cppcoreguidelines-pro-type-const-cast,
  -cppcoreguidelines-pro-type-reinterpret-cast,
  -cppcoreguidelines-pro-type-static-cast-downcast,
  -cppcoreguidelines-pro-type-union-access,
  -cppcoreguidelines-special-member-functions,
  -cppcoreguidelines-use-enum-class,
  -misc-const-correctness,
  -misc-include-cleaner,
  -misc-misplaced-const,
  -misc-no-recursion,
  -misc-non-private-member-variables-in-classes,
  -misc-use-anonymous-namespace,
  -misc-use-internal-linkage,
  -performance-enum-size,
  -performance-no-int-to-ptr,
  -portability-avoid-pragma-once,
]

HeaderFilterRegex: '.*'
ExcludeHeaderFilterRegex: '(builds|build|include/LIEF|utils/ordinals_lookup_tables_std|utils/ordinals_lookup_tables)/*'
