#!/usr/bin/sh
set -ex

export CXXFLAGS='-ffunction-sections -fdata-sections -fvisibility-inlines-hidden -static-libgcc'
export CFLAGS='-ffunction-sections -fdata-sections -static-libgcc'
export LDFLAGS='-Wl,--gc-sections -Wl,--strip-all'
export PYLIEF_CONF=/src/scripts/docker/config/pylinux-x64.toml
export LIEF_BUILD_DIR=/tmp/lief-build

$PYTHON_BINARY -m venv /tmp/lief_venv
source /tmp/lief_venv/bin/activate

python -m pip install            \
              tomli==2.0.1       \
              wheel==0.41.2      \
              setuptools==68.2.2


pushd /src/api/python
python -m pip -vvv wheel                  \
              --no-build-isolation        \
              --disable-pip-version-check \
              --wheel-dir=/src/wheel_stage .
popd

deactivate

find /src/wheel_stage -iname "*-cp${PYTHON_VERSION}-*" \
     -exec auditwheel repair -w /src/dist {} \;
