#!/usr/bin/bash
set -ex

export CXXFLAGS='-ffunction-sections -fdata-sections -fvisibility-inlines-hidden -static-libgcc'
export CFLAGS='-ffunction-sections -fdata-sections -static-libgcc'
export LDFLAGS='-Wl,--gc-sections'
export LIEF_BUILD_DIR=/tmp/lief-build
export PYLIEF_CONF=/src/scripts/docker/config/pylinux-aarch64.toml

$PYTHON_BINARY -m venv /tmp/lief_venv
source /tmp/lief_venv/bin/activate

python -m pip install -r /src/api/python/build-requirements.txt

pushd /src/api/python
# These exports need to set here to avoid pip install using the wrong platform
export _PYTHON_HOST_PLATFORM="manylinux2014-aarch64"
export SETUPTOOLS_EXT_SUFFIX=$($PYTHON_BINARY -c "import sysconfig;print(sysconfig.get_config_var('EXT_SUFFIX').replace('x86_64', 'aarch64'))")
export LIEF_TARGET_PYTHON_VERSION=$($PYTHON_BINARY -c "import sysconfig;print(sysconfig.get_python_version())")

python -m pip -vvv wheel                  \
              --no-build-isolation        \
              --disable-pip-version-check \
              --wheel-dir=/src/dist .
popd
