#!/usr/bin/sh
set -e
export LIEF_SAMPLES_DIR=/tmp/samples
export CXXFLAGS='-ffunction-sections -fdata-sections -fvisibility-inlines-hidden -static-libgcc'
export CFLAGS='-ffunction-sections -fdata-sections -static-libgcc'
export LDFLAGS='-Wl,--gc-sections'
export PYLIEF_CONF=/src/scripts/docker/config/pylinux-test-x64.toml

export LIEF_BUILD_DIR="/tmp/lief-build"

$PYTHON_BINARY -m venv /tmp/lief_venv
source /tmp/lief_venv/bin/activate

python -m pip install                            \
       -r /src/tests/requirements.txt            \
       -r /src/api/python/build-requirements.txt

mkdir -p ${LIEF_SAMPLES_DIR}

python tests/dl_samples.py ${LIEF_SAMPLES_DIR}
python -m pip -vvv install /src/api/python

# Run the Python test suite
python tests/run_pytest.py
python tests/run_tools_check.py ${LIEF_BUILD_DIR}/

ctest --output-on-failure --test-dir ${LIEF_BUILD_DIR}/

# Fuzzing
export PYTHONPATH="/src/tests:$PYTHONPATH"
python tests/elf/fuzzing.py                                    \
       ${LIEF_BUILD_DIR}/tests/Melkor/src/MELKOR/melkor                            \
       --input-seed ${LIEF_SAMPLES_DIR}/ELF/ELF64_x86-64_binary_ls.bin -n 100

python tests/elf/fuzzing.py                                    \
       ${LIEF_BUILD_DIR}/tests/Melkor/src/MELKOR/melkor                            \
       --input-seed ${LIEF_SAMPLES_DIR}/ELF/ELF64_x86-64_binary_openssl.bin -n 100

python tests/elf/fuzzing.py                             \
       ${LIEF_BUILD_DIR}/tests/Melkor/src/MELKOR/melkor \
       --input-seed ${LIEF_SAMPLES_DIR}/ELF/ELF64_x86-64_binary_nm.bin -n 100
