from typing import Any, ClassVar

import lief.Android # type: ignore

class ANDROID_VERSIONS:
    UNKNOWN: ClassVar[ANDROID_VERSIONS] = ...
    VERSION_601: ClassVar[ANDROID_VERSIONS] = ...
    VERSION_700: ClassVar[ANDROID_VERSIONS] = ...
    VERSION_710: ClassVar[ANDROID_VERSIONS] = ...
    VERSION_712: ClassVar[ANDROID_VERSIONS] = ...
    VERSION_800: ClassVar[ANDROID_VERSIONS] = ...
    VERSION_810: ClassVar[ANDROID_VERSIONS] = ...
    VERSION_900: ClassVar[ANDROID_VERSIONS] = ...
    __name__: str
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def from_value(arg: int, /) -> lief.Android.ANDROID_VERSIONS: ...
    def __ge__(self, other) -> bool: ...
    def __gt__(self, other) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> Any: ...
    def __int__(self) -> int: ...
    def __le__(self, other) -> bool: ...
    def __lt__(self, other) -> bool: ...
    @property
    def value(self) -> int: ...

def code_name(version: lief.Android.ANDROID_VERSIONS) -> str: ...
def version_string(version: lief.Android.ANDROID_VERSIONS) -> str: ...
