import os
from typing import Any, Final, Optional, Union, overload

import lief.ELF
import lief.runtime


class Module(lief.runtime.Module):
    @property
    def handle(self) -> Any: ...

    def dlsym(self, name: str) -> Any: ...

    @staticmethod
    def from_handle(handle: Any) -> Optional[Module]: ...

    @overload
    def parse_from_path(self) -> Optional[lief.ELF.Binary]: ...

    @overload
    def parse_from_path(self, config: lief.ELF.ParserConfig) -> Optional[lief.ELF.Binary]: ...

    @overload
    def parse_from_memory(self) -> Optional[lief.ELF.Binary]: ...

    @overload
    def parse_from_memory(self, config: lief.ELF.ParserConfig) -> Optional[lief.ELF.Binary]: ...

def dlopen(name: Union[str, os.PathLike]) -> Optional[Module]: ...

class Host:
    sys_name: Final[str] = ...

    sys_release: Final[str] = ...

    sys_version: Final[str] = ...

    hardware: Final[str] = ...

class Process(lief.runtime.Process):
    cmdline: Final[str] = ...

    glibc_version: Final[str] = ...
