import os
from typing import Any, Final, Optional, Union, overload

import lief.MachO
import lief.runtime


class Module(lief.runtime.Module):
    @property
    def handle(self) -> Any: ...

    def dlsym(self, name: str) -> Any: ...

    @staticmethod
    def from_handle(handle: Any) -> Optional[Module]: ...

    @overload
    def parse_from_path(self) -> Optional[lief.MachO.Binary]: ...

    @overload
    def parse_from_path(self, config: lief.MachO.ParserConfig) -> Optional[lief.MachO.Binary]: ...

    @overload
    def parse_from_memory(self) -> Optional[lief.MachO.Binary]: ...

    @overload
    def parse_from_memory(self, config: lief.MachO.ParserConfig) -> Optional[lief.MachO.Binary]: ...

def dlopen(name: Union[str, os.PathLike]) -> Optional[Module]: ...

class Host:
    class version_t:
        def __init__(self, major: int, minor: int, patch: int) -> None: ...

        major: int

        minor: int

        patch: int

        def __eq__(self, arg, /) -> bool: ...

        def __ne__(self, arg, /) -> bool: ...

        def __le__(self, arg: Host.version_t, /) -> bool: ...

        def __gt__(self, arg: Host.version_t, /) -> bool: ...

        def __ge__(self, arg: Host.version_t, /) -> bool: ...

        def __lt__(self, arg: Host.version_t, /) -> bool: ...

        @staticmethod
        def big_sur() -> Host.version_t: ...

        @staticmethod
        def monterey() -> Host.version_t: ...

        @staticmethod
        def ventura() -> Host.version_t: ...

        @staticmethod
        def sonoma() -> Host.version_t: ...

        @staticmethod
        def sequoia() -> Host.version_t: ...

        @staticmethod
        def tahoe() -> Host.version_t: ...

        def __str__(self) -> str: ...

    os_version_name: Final[str] = ...

    os_version: Final[Host.version_t] = ...

    is_sip_enabled: Final[bool] = ...

class Process(lief.runtime.Process):
    dyld_version: Final[str] = ...
