from collections.abc import Iterator, Mapping
import os
from typing import Any, Final, Optional, Union, overload

import lief
import lief.PE
import lief.runtime


class Module(lief.runtime.Module):
    @property
    def handle(self) -> Any: ...

    def dlsym(self, name: str) -> Any: ...

    @staticmethod
    def from_handle(handle: Any) -> Optional[Module]: ...

    @overload
    def parse_from_path(self) -> Optional[lief.PE.Binary]: ...

    @overload
    def parse_from_path(self, config: lief.PE.ParserConfig) -> Optional[lief.PE.Binary]: ...

    @overload
    def parse_from_memory(self) -> Optional[lief.PE.Binary]: ...

    @overload
    def parse_from_memory(self, config: lief.PE.ParserConfig) -> Optional[lief.PE.Binary]: ...

def dlopen(name: Union[str, os.PathLike]) -> Optional[Module]: ...

def find_module(name: str) -> Optional[Module]: ...

class Host:
    class version_t:
        @overload
        def __init__(self) -> None: ...

        @overload
        def __init__(self, major: int, minor: int, build_number: int) -> None: ...

        major: int

        minor: int

        build_number: int

        def __eq__(self, arg, /) -> bool: ...

        def __ne__(self, arg, /) -> bool: ...

        def __le__(self, arg: Host.version_t, /) -> bool: ...

        def __gt__(self, arg: Host.version_t, /) -> bool: ...

        def __ge__(self, arg: Host.version_t, /) -> bool: ...

        def __lt__(self, arg: Host.version_t, /) -> bool: ...

        def __str__(self) -> str: ...

    version: Final[Host.version_t] = ...

class LdrDataTableEntry:
    @property
    def dll_base(self) -> int: ...

    @property
    def entry_point(self) -> int: ...

    @property
    def size_of_image(self) -> int: ...

    @property
    def full_dll_name(self) -> str: ...

    @property
    def base_dll_name(self) -> str: ...

    @property
    def flags(self) -> int: ...

    @property
    def obsolete_load_count(self) -> int: ...

    @property
    def tls_index(self) -> int: ...

    @property
    def time_date_stamp(self) -> int: ...

    @property
    def entry_point_activation_context(self) -> int: ...

    @property
    def lock(self) -> int: ...

    @property
    def ddag_node(self) -> int | None: ...

    @property
    def load_context(self) -> int | None: ...

    @property
    def parent_dll_base(self) -> int | None: ...

    @property
    def switch_back_context(self) -> int | None: ...

    @property
    def original_base(self) -> int | None: ...

    @property
    def load_time(self) -> int | None: ...

    @property
    def base_name_hash_value(self) -> int | None: ...

    @property
    def load_reason(self) -> int | None: ...

    @property
    def implicit_path_options(self) -> int | None: ...

    @property
    def reference_count(self) -> int | None: ...

    @property
    def dependent_load_flags(self) -> int | None: ...

    @property
    def signing_level(self) -> int | None: ...

    @property
    def check_sum(self) -> int | None: ...

    @property
    def active_patch_image_base(self) -> int | None: ...

    @property
    def hot_patch_state(self) -> int | None: ...

    def __str__(self) -> str: ...

class PEB:
    @property
    def being_debugged(self) -> bool: ...

    @property
    def ldr(self) -> int: ...

    @property
    def process_parameters(self) -> int: ...

    @property
    def atl_thunk_slist_ptr(self) -> int: ...

    @property
    def atl_thunk_slist_ptr32(self) -> int: ...

    @property
    def post_process_init_routine(self) -> int: ...

    @property
    def session_id(self) -> int: ...

    @property
    def entries(self) -> Iterator[Optional[LdrDataTableEntry]]: ...

class Process(lief.runtime.Process):
    peb: Final[Optional[PEB]] = ...

class injection_context_t:
    def __init__(self) -> None: ...

    target_path: str

    args: str

    library: str

    @property
    def env(self) -> dict[str, str]: ...

    @env.setter
    def env(self, arg: Mapping[str, str], /) -> None: ...

def inject_spawn(ctx: injection_context_t) -> Union[lief.ok_t, lief.lief_errors]: ...
