#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Opcode {
    PHI,
    INLINEASM,
    INLINEASM_BR,
    CFI_INSTRUCTION,
    EH_LABEL,
    GC_LABEL,
    ANNOTATION_LABEL,
    KILL,
    EXTRACT_SUBREG,
    INSERT_SUBREG,
    IMPLICIT_DEF,
    INIT_UNDEF,
    SUBREG_TO_REG,
    COPY_TO_REGCLASS,
    DBG_VALUE,
    DBG_VALUE_LIST,
    DBG_INSTR_REF,
    DBG_PHI,
    DBG_LABEL,
    REG_SEQUENCE,
    COPY,
    COPY_LANEMASK,
    BUNDLE,
    LIFETIME_START,
    LIFETIME_END,
    PSEUDO_PROBE,
    ARITH_FENCE,
    STACKMAP,
    FENTRY_CALL,
    PATCHPOINT,
    LOAD_STACK_GUARD,
    PREALLOCATED_SETUP,
    PREALLOCATED_ARG,
    STATEPOINT,
    LOCAL_ESCAPE,
    FAULTING_OP,
    PATCHABLE_OP,
    PATCHABLE_FUNCTION_ENTER,
    PATCHABLE_RET,
    PATCHABLE_FUNCTION_EXIT,
    PATCHABLE_TAIL_CALL,
    PATCHABLE_EVENT_CALL,
    PATCHABLE_TYPED_EVENT_CALL,
    ICALL_BRANCH_FUNNEL,
    FAKE_USE,
    MEMBARRIER,
    JUMP_TABLE_DEBUG_INFO,
    RELOC_NONE,
    CONVERGENCECTRL_ENTRY,
    CONVERGENCECTRL_ANCHOR,
    CONVERGENCECTRL_LOOP,
    CONVERGENCECTRL_GLUE,
    G_ASSERT_SEXT,
    G_ASSERT_ZEXT,
    G_ASSERT_ALIGN,
    G_ADD,
    G_SUB,
    G_MUL,
    G_SDIV,
    G_UDIV,
    G_SREM,
    G_UREM,
    G_SDIVREM,
    G_UDIVREM,
    G_AND,
    G_OR,
    G_XOR,
    G_ABDS,
    G_ABDU,
    G_UAVGFLOOR,
    G_UAVGCEIL,
    G_SAVGFLOOR,
    G_SAVGCEIL,
    G_IMPLICIT_DEF,
    G_PHI,
    G_FRAME_INDEX,
    G_GLOBAL_VALUE,
    G_PTRAUTH_GLOBAL_VALUE,
    G_CONSTANT_POOL,
    G_EXTRACT,
    G_UNMERGE_VALUES,
    G_INSERT,
    G_MERGE_VALUES,
    G_BUILD_VECTOR,
    G_BUILD_VECTOR_TRUNC,
    G_CONCAT_VECTORS,
    G_PTRTOINT,
    G_INTTOPTR,
    G_BITCAST,
    G_FREEZE,
    G_CONSTANT_FOLD_BARRIER,
    G_INTRINSIC_FPTRUNC_ROUND,
    G_INTRINSIC_TRUNC,
    G_INTRINSIC_ROUND,
    G_INTRINSIC_LRINT,
    G_INTRINSIC_LLRINT,
    G_INTRINSIC_ROUNDEVEN,
    G_READCYCLECOUNTER,
    G_READSTEADYCOUNTER,
    G_LOAD,
    G_SEXTLOAD,
    G_ZEXTLOAD,
    G_FPEXTLOAD,
    G_INDEXED_LOAD,
    G_INDEXED_SEXTLOAD,
    G_INDEXED_ZEXTLOAD,
    G_STORE,
    G_FPTRUNCSTORE,
    G_INDEXED_STORE,
    G_ATOMIC_CMPXCHG_WITH_SUCCESS,
    G_ATOMIC_CMPXCHG,
    G_ATOMICRMW_XCHG,
    G_ATOMICRMW_ADD,
    G_ATOMICRMW_SUB,
    G_ATOMICRMW_AND,
    G_ATOMICRMW_NAND,
    G_ATOMICRMW_OR,
    G_ATOMICRMW_XOR,
    G_ATOMICRMW_MAX,
    G_ATOMICRMW_MIN,
    G_ATOMICRMW_UMAX,
    G_ATOMICRMW_UMIN,
    G_ATOMICRMW_FADD,
    G_ATOMICRMW_FSUB,
    G_ATOMICRMW_FMAX,
    G_ATOMICRMW_FMIN,
    G_ATOMICRMW_FMAXIMUM,
    G_ATOMICRMW_FMINIMUM,
    G_ATOMICRMW_FMAXIMUMNUM,
    G_ATOMICRMW_FMINIMUMNUM,
    G_ATOMICRMW_UINC_WRAP,
    G_ATOMICRMW_UDEC_WRAP,
    G_ATOMICRMW_USUB_COND,
    G_ATOMICRMW_USUB_SAT,
    G_FENCE,
    G_PREFETCH,
    G_BRCOND,
    G_BRINDIRECT,
    G_INVOKE_REGION_START,
    G_INTRINSIC,
    G_INTRINSIC_W_SIDE_EFFECTS,
    G_INTRINSIC_CONVERGENT,
    G_INTRINSIC_CONVERGENT_W_SIDE_EFFECTS,
    G_ANYEXT,
    G_TRUNC,
    G_TRUNC_SSAT_S,
    G_TRUNC_SSAT_U,
    G_TRUNC_USAT_U,
    G_CONSTANT,
    G_FCONSTANT,
    G_VASTART,
    G_VAARG,
    G_SEXT,
    G_SEXT_INREG,
    G_ZEXT,
    G_SHL,
    G_LSHR,
    G_ASHR,
    G_FSHL,
    G_FSHR,
    G_ROTR,
    G_ROTL,
    G_ICMP,
    G_FCMP,
    G_SCMP,
    G_UCMP,
    G_SELECT,
    G_UADDO,
    G_UADDE,
    G_USUBO,
    G_USUBE,
    G_SADDO,
    G_SADDE,
    G_SSUBO,
    G_SSUBE,
    G_UMULO,
    G_SMULO,
    G_UMULH,
    G_SMULH,
    G_UADDSAT,
    G_SADDSAT,
    G_USUBSAT,
    G_SSUBSAT,
    G_USHLSAT,
    G_SSHLSAT,
    G_SMULFIX,
    G_UMULFIX,
    G_SMULFIXSAT,
    G_UMULFIXSAT,
    G_SDIVFIX,
    G_UDIVFIX,
    G_SDIVFIXSAT,
    G_UDIVFIXSAT,
    G_FADD,
    G_FSUB,
    G_FMUL,
    G_FMA,
    G_FMAD,
    G_FDIV,
    G_FREM,
    G_FMODF,
    G_FPOW,
    G_FPOWI,
    G_FEXP,
    G_FEXP2,
    G_FEXP10,
    G_FLOG,
    G_FLOG2,
    G_FLOG10,
    G_FLDEXP,
    G_FFREXP,
    G_FNEG,
    G_FPEXT,
    G_FPTRUNC,
    G_FPTOSI,
    G_FPTOUI,
    G_SITOFP,
    G_UITOFP,
    G_FPTOSI_SAT,
    G_FPTOUI_SAT,
    G_FABS,
    G_FCOPYSIGN,
    G_IS_FPCLASS,
    G_FCANONICALIZE,
    G_FMINNUM,
    G_FMAXNUM,
    G_FMINNUM_IEEE,
    G_FMAXNUM_IEEE,
    G_FMINIMUM,
    G_FMAXIMUM,
    G_FMINIMUMNUM,
    G_FMAXIMUMNUM,
    G_GET_FPENV,
    G_SET_FPENV,
    G_RESET_FPENV,
    G_GET_FPMODE,
    G_SET_FPMODE,
    G_RESET_FPMODE,
    G_GET_ROUNDING,
    G_SET_ROUNDING,
    G_PTR_ADD,
    G_PTRMASK,
    G_SMIN,
    G_SMAX,
    G_UMIN,
    G_UMAX,
    G_ABS,
    G_LROUND,
    G_LLROUND,
    G_BR,
    G_BRJT,
    G_VSCALE,
    G_INSERT_SUBVECTOR,
    G_EXTRACT_SUBVECTOR,
    G_INSERT_VECTOR_ELT,
    G_EXTRACT_VECTOR_ELT,
    G_SHUFFLE_VECTOR,
    G_SPLAT_VECTOR,
    G_STEP_VECTOR,
    G_VECTOR_COMPRESS,
    G_CTTZ,
    G_CTTZ_ZERO_POISON,
    G_CTLZ,
    G_CTLZ_ZERO_POISON,
    G_CTLS,
    G_CTPOP,
    G_BSWAP,
    G_BITREVERSE,
    G_CLMUL,
    G_FCEIL,
    G_FCOS,
    G_FSIN,
    G_FSINCOS,
    G_FTAN,
    G_FACOS,
    G_FASIN,
    G_FATAN,
    G_FATAN2,
    G_FCOSH,
    G_FSINH,
    G_FTANH,
    G_FSQRT,
    G_FFLOOR,
    G_FRINT,
    G_FNEARBYINT,
    G_ADDRSPACE_CAST,
    G_BLOCK_ADDR,
    G_JUMP_TABLE,
    G_DYN_STACKALLOC,
    G_STACKSAVE,
    G_STACKRESTORE,
    G_STRICT_FADD,
    G_STRICT_FSUB,
    G_STRICT_FMUL,
    G_STRICT_FDIV,
    G_STRICT_FREM,
    G_STRICT_FMA,
    G_STRICT_FSQRT,
    G_STRICT_FLDEXP,
    G_STRICT_FCMP,
    G_STRICT_FCMPS,
    G_READ_REGISTER,
    G_WRITE_REGISTER,
    G_MEMCPY,
    G_MEMCPY_INLINE,
    G_MEMMOVE,
    G_MEMSET,
    G_BZERO,
    G_MEMSET_INLINE,
    G_TRAP,
    G_DEBUGTRAP,
    G_UBSANTRAP,
    G_VECREDUCE_SEQ_FADD,
    G_VECREDUCE_SEQ_FMUL,
    G_VECREDUCE_FADD,
    G_VECREDUCE_FMUL,
    G_VECREDUCE_FMAX,
    G_VECREDUCE_FMIN,
    G_VECREDUCE_FMAXIMUM,
    G_VECREDUCE_FMINIMUM,
    G_VECREDUCE_ADD,
    G_VECREDUCE_MUL,
    G_VECREDUCE_AND,
    G_VECREDUCE_OR,
    G_VECREDUCE_XOR,
    G_VECREDUCE_SMAX,
    G_VECREDUCE_SMIN,
    G_VECREDUCE_UMAX,
    G_VECREDUCE_UMIN,
    G_SBFX,
    G_UBFX,
    ADJCALLSTACKDOWN,
    ADJCALLSTACKUP,
    FI_ri,
    LDIMM64,
    LOAD_STACK_ARG_PSEUDO,
    MEMCPY,
    STORE_STACK_ARG_IMM_PSEUDO,
    STORE_STACK_ARG_PSEUDO,
    Select,
    Select_32,
    Select_32_64,
    Select_64_32,
    Select_Ri,
    Select_Ri_32,
    Select_Ri_32_64,
    Select_Ri_64_32,
    ADDR_SPACE_CAST,
    ADD_ri,
    ADD_ri_32,
    ADD_rr,
    ADD_rr_32,
    AND_ri,
    AND_ri_32,
    AND_rr,
    AND_rr_32,
    BE16,
    BE32,
    BE64,
    BSWAP16,
    BSWAP32,
    BSWAP64,
    CMPXCHGD,
    CMPXCHGW32,
    CORE_LD32,
    CORE_LD64,
    CORE_SHIFT,
    CORE_ST,
    DIV_ri,
    DIV_ri_32,
    DIV_rr,
    DIV_rr_32,
    JAL,
    JALX,
    JCOND,
    JEQ_ri,
    JEQ_ri_32,
    JEQ_rr,
    JEQ_rr_32,
    JMP,
    JMPL,
    JNE_ri,
    JNE_ri_32,
    JNE_rr,
    JNE_rr_32,
    JSET_ri,
    JSET_ri_32,
    JSET_rr,
    JSET_rr_32,
    JSGE_ri,
    JSGE_ri_32,
    JSGE_rr,
    JSGE_rr_32,
    JSGT_ri,
    JSGT_ri_32,
    JSGT_rr,
    JSGT_rr_32,
    JSLE_ri,
    JSLE_ri_32,
    JSLE_rr,
    JSLE_rr_32,
    JSLT_ri,
    JSLT_ri_32,
    JSLT_rr,
    JSLT_rr_32,
    JUGE_ri,
    JUGE_ri_32,
    JUGE_rr,
    JUGE_rr_32,
    JUGT_ri,
    JUGT_ri_32,
    JUGT_rr,
    JUGT_rr_32,
    JULE_ri,
    JULE_ri_32,
    JULE_rr,
    JULE_rr_32,
    JULT_ri,
    JULT_ri_32,
    JULT_rr,
    JULT_rr_32,
    JX,
    LDB,
    LDB32,
    LDBACQ32,
    LDBSX,
    LDD,
    LDDACQ,
    LDH,
    LDH32,
    LDHACQ32,
    LDHSX,
    LDW,
    LDW32,
    LDWACQ32,
    LDWSX,
    LD_ABS_B,
    LD_ABS_H,
    LD_ABS_W,
    LD_IND_B,
    LD_IND_H,
    LD_IND_W,
    LD_imm64,
    LD_pseudo,
    LE16,
    LE32,
    LE64,
    MOD_ri,
    MOD_ri_32,
    MOD_rr,
    MOD_rr_32,
    MOVSX_rr_16,
    MOVSX_rr_32,
    MOVSX_rr_32_16,
    MOVSX_rr_32_8,
    MOVSX_rr_8,
    MOV_32_64,
    MOV_ri,
    MOV_ri_32,
    MOV_rr,
    MOV_rr_32,
    MUL_ri,
    MUL_ri_32,
    MUL_rr,
    MUL_rr_32,
    NEG_32,
    NEG_64,
    NOP,
    OR_ri,
    OR_ri_32,
    OR_rr,
    OR_rr_32,
    RET,
    SDIV_ri,
    SDIV_ri_32,
    SDIV_rr,
    SDIV_rr_32,
    SLL_ri,
    SLL_ri_32,
    SLL_rr,
    SLL_rr_32,
    SMOD_ri,
    SMOD_ri_32,
    SMOD_rr,
    SMOD_rr_32,
    SRA_ri,
    SRA_ri_32,
    SRA_rr,
    SRA_rr_32,
    SRL_ri,
    SRL_ri_32,
    SRL_rr,
    SRL_rr_32,
    STB,
    STB32,
    STBREL32,
    STB_imm,
    STD,
    STDREL,
    STD_imm,
    STH,
    STH32,
    STHREL32,
    STH_imm,
    STW,
    STW32,
    STWREL32,
    STW_imm,
    SUB_ri,
    SUB_ri_32,
    SUB_rr,
    SUB_rr_32,
    XADDD,
    XADDW,
    XADDW32,
    XANDD,
    XANDW32,
    XCHGD,
    XCHGW32,
    XFADDD,
    XFADDW32,
    XFANDD,
    XFANDW32,
    XFORD,
    XFORW32,
    XFXORD,
    XFXORW32,
    XORD,
    XORW32,
    XOR_ri,
    XOR_ri_32,
    XOR_rr,
    XOR_rr_32,
    XXORD,
    XXORW32,
    INSTRUCTION_LIST_END,
    UNKNOWN(u64),
}

impl From<u64> for Opcode {
    fn from(value: u64) -> Self {
        match value {
            0 => Opcode::PHI,
            1 => Opcode::INLINEASM,
            2 => Opcode::INLINEASM_BR,
            3 => Opcode::CFI_INSTRUCTION,
            4 => Opcode::EH_LABEL,
            5 => Opcode::GC_LABEL,
            6 => Opcode::ANNOTATION_LABEL,
            7 => Opcode::KILL,
            8 => Opcode::EXTRACT_SUBREG,
            9 => Opcode::INSERT_SUBREG,
            10 => Opcode::IMPLICIT_DEF,
            11 => Opcode::INIT_UNDEF,
            12 => Opcode::SUBREG_TO_REG,
            13 => Opcode::COPY_TO_REGCLASS,
            14 => Opcode::DBG_VALUE,
            15 => Opcode::DBG_VALUE_LIST,
            16 => Opcode::DBG_INSTR_REF,
            17 => Opcode::DBG_PHI,
            18 => Opcode::DBG_LABEL,
            19 => Opcode::REG_SEQUENCE,
            20 => Opcode::COPY,
            21 => Opcode::COPY_LANEMASK,
            22 => Opcode::BUNDLE,
            23 => Opcode::LIFETIME_START,
            24 => Opcode::LIFETIME_END,
            25 => Opcode::PSEUDO_PROBE,
            26 => Opcode::ARITH_FENCE,
            27 => Opcode::STACKMAP,
            28 => Opcode::FENTRY_CALL,
            29 => Opcode::PATCHPOINT,
            30 => Opcode::LOAD_STACK_GUARD,
            31 => Opcode::PREALLOCATED_SETUP,
            32 => Opcode::PREALLOCATED_ARG,
            33 => Opcode::STATEPOINT,
            34 => Opcode::LOCAL_ESCAPE,
            35 => Opcode::FAULTING_OP,
            36 => Opcode::PATCHABLE_OP,
            37 => Opcode::PATCHABLE_FUNCTION_ENTER,
            38 => Opcode::PATCHABLE_RET,
            39 => Opcode::PATCHABLE_FUNCTION_EXIT,
            40 => Opcode::PATCHABLE_TAIL_CALL,
            41 => Opcode::PATCHABLE_EVENT_CALL,
            42 => Opcode::PATCHABLE_TYPED_EVENT_CALL,
            43 => Opcode::ICALL_BRANCH_FUNNEL,
            44 => Opcode::FAKE_USE,
            45 => Opcode::MEMBARRIER,
            46 => Opcode::JUMP_TABLE_DEBUG_INFO,
            47 => Opcode::RELOC_NONE,
            48 => Opcode::CONVERGENCECTRL_ENTRY,
            49 => Opcode::CONVERGENCECTRL_ANCHOR,
            50 => Opcode::CONVERGENCECTRL_LOOP,
            51 => Opcode::CONVERGENCECTRL_GLUE,
            52 => Opcode::G_ASSERT_SEXT,
            53 => Opcode::G_ASSERT_ZEXT,
            54 => Opcode::G_ASSERT_ALIGN,
            55 => Opcode::G_ADD,
            56 => Opcode::G_SUB,
            57 => Opcode::G_MUL,
            58 => Opcode::G_SDIV,
            59 => Opcode::G_UDIV,
            60 => Opcode::G_SREM,
            61 => Opcode::G_UREM,
            62 => Opcode::G_SDIVREM,
            63 => Opcode::G_UDIVREM,
            64 => Opcode::G_AND,
            65 => Opcode::G_OR,
            66 => Opcode::G_XOR,
            67 => Opcode::G_ABDS,
            68 => Opcode::G_ABDU,
            69 => Opcode::G_UAVGFLOOR,
            70 => Opcode::G_UAVGCEIL,
            71 => Opcode::G_SAVGFLOOR,
            72 => Opcode::G_SAVGCEIL,
            73 => Opcode::G_IMPLICIT_DEF,
            74 => Opcode::G_PHI,
            75 => Opcode::G_FRAME_INDEX,
            76 => Opcode::G_GLOBAL_VALUE,
            77 => Opcode::G_PTRAUTH_GLOBAL_VALUE,
            78 => Opcode::G_CONSTANT_POOL,
            79 => Opcode::G_EXTRACT,
            80 => Opcode::G_UNMERGE_VALUES,
            81 => Opcode::G_INSERT,
            82 => Opcode::G_MERGE_VALUES,
            83 => Opcode::G_BUILD_VECTOR,
            84 => Opcode::G_BUILD_VECTOR_TRUNC,
            85 => Opcode::G_CONCAT_VECTORS,
            86 => Opcode::G_PTRTOINT,
            87 => Opcode::G_INTTOPTR,
            88 => Opcode::G_BITCAST,
            89 => Opcode::G_FREEZE,
            90 => Opcode::G_CONSTANT_FOLD_BARRIER,
            91 => Opcode::G_INTRINSIC_FPTRUNC_ROUND,
            92 => Opcode::G_INTRINSIC_TRUNC,
            93 => Opcode::G_INTRINSIC_ROUND,
            94 => Opcode::G_INTRINSIC_LRINT,
            95 => Opcode::G_INTRINSIC_LLRINT,
            96 => Opcode::G_INTRINSIC_ROUNDEVEN,
            97 => Opcode::G_READCYCLECOUNTER,
            98 => Opcode::G_READSTEADYCOUNTER,
            99 => Opcode::G_LOAD,
            100 => Opcode::G_SEXTLOAD,
            101 => Opcode::G_ZEXTLOAD,
            102 => Opcode::G_FPEXTLOAD,
            103 => Opcode::G_INDEXED_LOAD,
            104 => Opcode::G_INDEXED_SEXTLOAD,
            105 => Opcode::G_INDEXED_ZEXTLOAD,
            106 => Opcode::G_STORE,
            107 => Opcode::G_FPTRUNCSTORE,
            108 => Opcode::G_INDEXED_STORE,
            109 => Opcode::G_ATOMIC_CMPXCHG_WITH_SUCCESS,
            110 => Opcode::G_ATOMIC_CMPXCHG,
            111 => Opcode::G_ATOMICRMW_XCHG,
            112 => Opcode::G_ATOMICRMW_ADD,
            113 => Opcode::G_ATOMICRMW_SUB,
            114 => Opcode::G_ATOMICRMW_AND,
            115 => Opcode::G_ATOMICRMW_NAND,
            116 => Opcode::G_ATOMICRMW_OR,
            117 => Opcode::G_ATOMICRMW_XOR,
            118 => Opcode::G_ATOMICRMW_MAX,
            119 => Opcode::G_ATOMICRMW_MIN,
            120 => Opcode::G_ATOMICRMW_UMAX,
            121 => Opcode::G_ATOMICRMW_UMIN,
            122 => Opcode::G_ATOMICRMW_FADD,
            123 => Opcode::G_ATOMICRMW_FSUB,
            124 => Opcode::G_ATOMICRMW_FMAX,
            125 => Opcode::G_ATOMICRMW_FMIN,
            126 => Opcode::G_ATOMICRMW_FMAXIMUM,
            127 => Opcode::G_ATOMICRMW_FMINIMUM,
            128 => Opcode::G_ATOMICRMW_FMAXIMUMNUM,
            129 => Opcode::G_ATOMICRMW_FMINIMUMNUM,
            130 => Opcode::G_ATOMICRMW_UINC_WRAP,
            131 => Opcode::G_ATOMICRMW_UDEC_WRAP,
            132 => Opcode::G_ATOMICRMW_USUB_COND,
            133 => Opcode::G_ATOMICRMW_USUB_SAT,
            134 => Opcode::G_FENCE,
            135 => Opcode::G_PREFETCH,
            136 => Opcode::G_BRCOND,
            137 => Opcode::G_BRINDIRECT,
            138 => Opcode::G_INVOKE_REGION_START,
            139 => Opcode::G_INTRINSIC,
            140 => Opcode::G_INTRINSIC_W_SIDE_EFFECTS,
            141 => Opcode::G_INTRINSIC_CONVERGENT,
            142 => Opcode::G_INTRINSIC_CONVERGENT_W_SIDE_EFFECTS,
            143 => Opcode::G_ANYEXT,
            144 => Opcode::G_TRUNC,
            145 => Opcode::G_TRUNC_SSAT_S,
            146 => Opcode::G_TRUNC_SSAT_U,
            147 => Opcode::G_TRUNC_USAT_U,
            148 => Opcode::G_CONSTANT,
            149 => Opcode::G_FCONSTANT,
            150 => Opcode::G_VASTART,
            151 => Opcode::G_VAARG,
            152 => Opcode::G_SEXT,
            153 => Opcode::G_SEXT_INREG,
            154 => Opcode::G_ZEXT,
            155 => Opcode::G_SHL,
            156 => Opcode::G_LSHR,
            157 => Opcode::G_ASHR,
            158 => Opcode::G_FSHL,
            159 => Opcode::G_FSHR,
            160 => Opcode::G_ROTR,
            161 => Opcode::G_ROTL,
            162 => Opcode::G_ICMP,
            163 => Opcode::G_FCMP,
            164 => Opcode::G_SCMP,
            165 => Opcode::G_UCMP,
            166 => Opcode::G_SELECT,
            167 => Opcode::G_UADDO,
            168 => Opcode::G_UADDE,
            169 => Opcode::G_USUBO,
            170 => Opcode::G_USUBE,
            171 => Opcode::G_SADDO,
            172 => Opcode::G_SADDE,
            173 => Opcode::G_SSUBO,
            174 => Opcode::G_SSUBE,
            175 => Opcode::G_UMULO,
            176 => Opcode::G_SMULO,
            177 => Opcode::G_UMULH,
            178 => Opcode::G_SMULH,
            179 => Opcode::G_UADDSAT,
            180 => Opcode::G_SADDSAT,
            181 => Opcode::G_USUBSAT,
            182 => Opcode::G_SSUBSAT,
            183 => Opcode::G_USHLSAT,
            184 => Opcode::G_SSHLSAT,
            185 => Opcode::G_SMULFIX,
            186 => Opcode::G_UMULFIX,
            187 => Opcode::G_SMULFIXSAT,
            188 => Opcode::G_UMULFIXSAT,
            189 => Opcode::G_SDIVFIX,
            190 => Opcode::G_UDIVFIX,
            191 => Opcode::G_SDIVFIXSAT,
            192 => Opcode::G_UDIVFIXSAT,
            193 => Opcode::G_FADD,
            194 => Opcode::G_FSUB,
            195 => Opcode::G_FMUL,
            196 => Opcode::G_FMA,
            197 => Opcode::G_FMAD,
            198 => Opcode::G_FDIV,
            199 => Opcode::G_FREM,
            200 => Opcode::G_FMODF,
            201 => Opcode::G_FPOW,
            202 => Opcode::G_FPOWI,
            203 => Opcode::G_FEXP,
            204 => Opcode::G_FEXP2,
            205 => Opcode::G_FEXP10,
            206 => Opcode::G_FLOG,
            207 => Opcode::G_FLOG2,
            208 => Opcode::G_FLOG10,
            209 => Opcode::G_FLDEXP,
            210 => Opcode::G_FFREXP,
            211 => Opcode::G_FNEG,
            212 => Opcode::G_FPEXT,
            213 => Opcode::G_FPTRUNC,
            214 => Opcode::G_FPTOSI,
            215 => Opcode::G_FPTOUI,
            216 => Opcode::G_SITOFP,
            217 => Opcode::G_UITOFP,
            218 => Opcode::G_FPTOSI_SAT,
            219 => Opcode::G_FPTOUI_SAT,
            220 => Opcode::G_FABS,
            221 => Opcode::G_FCOPYSIGN,
            222 => Opcode::G_IS_FPCLASS,
            223 => Opcode::G_FCANONICALIZE,
            224 => Opcode::G_FMINNUM,
            225 => Opcode::G_FMAXNUM,
            226 => Opcode::G_FMINNUM_IEEE,
            227 => Opcode::G_FMAXNUM_IEEE,
            228 => Opcode::G_FMINIMUM,
            229 => Opcode::G_FMAXIMUM,
            230 => Opcode::G_FMINIMUMNUM,
            231 => Opcode::G_FMAXIMUMNUM,
            232 => Opcode::G_GET_FPENV,
            233 => Opcode::G_SET_FPENV,
            234 => Opcode::G_RESET_FPENV,
            235 => Opcode::G_GET_FPMODE,
            236 => Opcode::G_SET_FPMODE,
            237 => Opcode::G_RESET_FPMODE,
            238 => Opcode::G_GET_ROUNDING,
            239 => Opcode::G_SET_ROUNDING,
            240 => Opcode::G_PTR_ADD,
            241 => Opcode::G_PTRMASK,
            242 => Opcode::G_SMIN,
            243 => Opcode::G_SMAX,
            244 => Opcode::G_UMIN,
            245 => Opcode::G_UMAX,
            246 => Opcode::G_ABS,
            247 => Opcode::G_LROUND,
            248 => Opcode::G_LLROUND,
            249 => Opcode::G_BR,
            250 => Opcode::G_BRJT,
            251 => Opcode::G_VSCALE,
            252 => Opcode::G_INSERT_SUBVECTOR,
            253 => Opcode::G_EXTRACT_SUBVECTOR,
            254 => Opcode::G_INSERT_VECTOR_ELT,
            255 => Opcode::G_EXTRACT_VECTOR_ELT,
            256 => Opcode::G_SHUFFLE_VECTOR,
            257 => Opcode::G_SPLAT_VECTOR,
            258 => Opcode::G_STEP_VECTOR,
            259 => Opcode::G_VECTOR_COMPRESS,
            260 => Opcode::G_CTTZ,
            261 => Opcode::G_CTTZ_ZERO_POISON,
            262 => Opcode::G_CTLZ,
            263 => Opcode::G_CTLZ_ZERO_POISON,
            264 => Opcode::G_CTLS,
            265 => Opcode::G_CTPOP,
            266 => Opcode::G_BSWAP,
            267 => Opcode::G_BITREVERSE,
            268 => Opcode::G_CLMUL,
            269 => Opcode::G_FCEIL,
            270 => Opcode::G_FCOS,
            271 => Opcode::G_FSIN,
            272 => Opcode::G_FSINCOS,
            273 => Opcode::G_FTAN,
            274 => Opcode::G_FACOS,
            275 => Opcode::G_FASIN,
            276 => Opcode::G_FATAN,
            277 => Opcode::G_FATAN2,
            278 => Opcode::G_FCOSH,
            279 => Opcode::G_FSINH,
            280 => Opcode::G_FTANH,
            281 => Opcode::G_FSQRT,
            282 => Opcode::G_FFLOOR,
            283 => Opcode::G_FRINT,
            284 => Opcode::G_FNEARBYINT,
            285 => Opcode::G_ADDRSPACE_CAST,
            286 => Opcode::G_BLOCK_ADDR,
            287 => Opcode::G_JUMP_TABLE,
            288 => Opcode::G_DYN_STACKALLOC,
            289 => Opcode::G_STACKSAVE,
            290 => Opcode::G_STACKRESTORE,
            291 => Opcode::G_STRICT_FADD,
            292 => Opcode::G_STRICT_FSUB,
            293 => Opcode::G_STRICT_FMUL,
            294 => Opcode::G_STRICT_FDIV,
            295 => Opcode::G_STRICT_FREM,
            296 => Opcode::G_STRICT_FMA,
            297 => Opcode::G_STRICT_FSQRT,
            298 => Opcode::G_STRICT_FLDEXP,
            299 => Opcode::G_STRICT_FCMP,
            300 => Opcode::G_STRICT_FCMPS,
            301 => Opcode::G_READ_REGISTER,
            302 => Opcode::G_WRITE_REGISTER,
            303 => Opcode::G_MEMCPY,
            304 => Opcode::G_MEMCPY_INLINE,
            305 => Opcode::G_MEMMOVE,
            306 => Opcode::G_MEMSET,
            307 => Opcode::G_BZERO,
            308 => Opcode::G_MEMSET_INLINE,
            309 => Opcode::G_TRAP,
            310 => Opcode::G_DEBUGTRAP,
            311 => Opcode::G_UBSANTRAP,
            312 => Opcode::G_VECREDUCE_SEQ_FADD,
            313 => Opcode::G_VECREDUCE_SEQ_FMUL,
            314 => Opcode::G_VECREDUCE_FADD,
            315 => Opcode::G_VECREDUCE_FMUL,
            316 => Opcode::G_VECREDUCE_FMAX,
            317 => Opcode::G_VECREDUCE_FMIN,
            318 => Opcode::G_VECREDUCE_FMAXIMUM,
            319 => Opcode::G_VECREDUCE_FMINIMUM,
            320 => Opcode::G_VECREDUCE_ADD,
            321 => Opcode::G_VECREDUCE_MUL,
            322 => Opcode::G_VECREDUCE_AND,
            323 => Opcode::G_VECREDUCE_OR,
            324 => Opcode::G_VECREDUCE_XOR,
            325 => Opcode::G_VECREDUCE_SMAX,
            326 => Opcode::G_VECREDUCE_SMIN,
            327 => Opcode::G_VECREDUCE_UMAX,
            328 => Opcode::G_VECREDUCE_UMIN,
            329 => Opcode::G_SBFX,
            330 => Opcode::G_UBFX,
            331 => Opcode::ADJCALLSTACKDOWN,
            332 => Opcode::ADJCALLSTACKUP,
            333 => Opcode::FI_ri,
            334 => Opcode::LDIMM64,
            335 => Opcode::LOAD_STACK_ARG_PSEUDO,
            336 => Opcode::MEMCPY,
            337 => Opcode::STORE_STACK_ARG_IMM_PSEUDO,
            338 => Opcode::STORE_STACK_ARG_PSEUDO,
            339 => Opcode::Select,
            340 => Opcode::Select_32,
            341 => Opcode::Select_32_64,
            342 => Opcode::Select_64_32,
            343 => Opcode::Select_Ri,
            344 => Opcode::Select_Ri_32,
            345 => Opcode::Select_Ri_32_64,
            346 => Opcode::Select_Ri_64_32,
            347 => Opcode::ADDR_SPACE_CAST,
            348 => Opcode::ADD_ri,
            349 => Opcode::ADD_ri_32,
            350 => Opcode::ADD_rr,
            351 => Opcode::ADD_rr_32,
            352 => Opcode::AND_ri,
            353 => Opcode::AND_ri_32,
            354 => Opcode::AND_rr,
            355 => Opcode::AND_rr_32,
            356 => Opcode::BE16,
            357 => Opcode::BE32,
            358 => Opcode::BE64,
            359 => Opcode::BSWAP16,
            360 => Opcode::BSWAP32,
            361 => Opcode::BSWAP64,
            362 => Opcode::CMPXCHGD,
            363 => Opcode::CMPXCHGW32,
            364 => Opcode::CORE_LD32,
            365 => Opcode::CORE_LD64,
            366 => Opcode::CORE_SHIFT,
            367 => Opcode::CORE_ST,
            368 => Opcode::DIV_ri,
            369 => Opcode::DIV_ri_32,
            370 => Opcode::DIV_rr,
            371 => Opcode::DIV_rr_32,
            372 => Opcode::JAL,
            373 => Opcode::JALX,
            374 => Opcode::JCOND,
            375 => Opcode::JEQ_ri,
            376 => Opcode::JEQ_ri_32,
            377 => Opcode::JEQ_rr,
            378 => Opcode::JEQ_rr_32,
            379 => Opcode::JMP,
            380 => Opcode::JMPL,
            381 => Opcode::JNE_ri,
            382 => Opcode::JNE_ri_32,
            383 => Opcode::JNE_rr,
            384 => Opcode::JNE_rr_32,
            385 => Opcode::JSET_ri,
            386 => Opcode::JSET_ri_32,
            387 => Opcode::JSET_rr,
            388 => Opcode::JSET_rr_32,
            389 => Opcode::JSGE_ri,
            390 => Opcode::JSGE_ri_32,
            391 => Opcode::JSGE_rr,
            392 => Opcode::JSGE_rr_32,
            393 => Opcode::JSGT_ri,
            394 => Opcode::JSGT_ri_32,
            395 => Opcode::JSGT_rr,
            396 => Opcode::JSGT_rr_32,
            397 => Opcode::JSLE_ri,
            398 => Opcode::JSLE_ri_32,
            399 => Opcode::JSLE_rr,
            400 => Opcode::JSLE_rr_32,
            401 => Opcode::JSLT_ri,
            402 => Opcode::JSLT_ri_32,
            403 => Opcode::JSLT_rr,
            404 => Opcode::JSLT_rr_32,
            405 => Opcode::JUGE_ri,
            406 => Opcode::JUGE_ri_32,
            407 => Opcode::JUGE_rr,
            408 => Opcode::JUGE_rr_32,
            409 => Opcode::JUGT_ri,
            410 => Opcode::JUGT_ri_32,
            411 => Opcode::JUGT_rr,
            412 => Opcode::JUGT_rr_32,
            413 => Opcode::JULE_ri,
            414 => Opcode::JULE_ri_32,
            415 => Opcode::JULE_rr,
            416 => Opcode::JULE_rr_32,
            417 => Opcode::JULT_ri,
            418 => Opcode::JULT_ri_32,
            419 => Opcode::JULT_rr,
            420 => Opcode::JULT_rr_32,
            421 => Opcode::JX,
            422 => Opcode::LDB,
            423 => Opcode::LDB32,
            424 => Opcode::LDBACQ32,
            425 => Opcode::LDBSX,
            426 => Opcode::LDD,
            427 => Opcode::LDDACQ,
            428 => Opcode::LDH,
            429 => Opcode::LDH32,
            430 => Opcode::LDHACQ32,
            431 => Opcode::LDHSX,
            432 => Opcode::LDW,
            433 => Opcode::LDW32,
            434 => Opcode::LDWACQ32,
            435 => Opcode::LDWSX,
            436 => Opcode::LD_ABS_B,
            437 => Opcode::LD_ABS_H,
            438 => Opcode::LD_ABS_W,
            439 => Opcode::LD_IND_B,
            440 => Opcode::LD_IND_H,
            441 => Opcode::LD_IND_W,
            442 => Opcode::LD_imm64,
            443 => Opcode::LD_pseudo,
            444 => Opcode::LE16,
            445 => Opcode::LE32,
            446 => Opcode::LE64,
            447 => Opcode::MOD_ri,
            448 => Opcode::MOD_ri_32,
            449 => Opcode::MOD_rr,
            450 => Opcode::MOD_rr_32,
            451 => Opcode::MOVSX_rr_16,
            452 => Opcode::MOVSX_rr_32,
            453 => Opcode::MOVSX_rr_32_16,
            454 => Opcode::MOVSX_rr_32_8,
            455 => Opcode::MOVSX_rr_8,
            456 => Opcode::MOV_32_64,
            457 => Opcode::MOV_ri,
            458 => Opcode::MOV_ri_32,
            459 => Opcode::MOV_rr,
            460 => Opcode::MOV_rr_32,
            461 => Opcode::MUL_ri,
            462 => Opcode::MUL_ri_32,
            463 => Opcode::MUL_rr,
            464 => Opcode::MUL_rr_32,
            465 => Opcode::NEG_32,
            466 => Opcode::NEG_64,
            467 => Opcode::NOP,
            468 => Opcode::OR_ri,
            469 => Opcode::OR_ri_32,
            470 => Opcode::OR_rr,
            471 => Opcode::OR_rr_32,
            472 => Opcode::RET,
            473 => Opcode::SDIV_ri,
            474 => Opcode::SDIV_ri_32,
            475 => Opcode::SDIV_rr,
            476 => Opcode::SDIV_rr_32,
            477 => Opcode::SLL_ri,
            478 => Opcode::SLL_ri_32,
            479 => Opcode::SLL_rr,
            480 => Opcode::SLL_rr_32,
            481 => Opcode::SMOD_ri,
            482 => Opcode::SMOD_ri_32,
            483 => Opcode::SMOD_rr,
            484 => Opcode::SMOD_rr_32,
            485 => Opcode::SRA_ri,
            486 => Opcode::SRA_ri_32,
            487 => Opcode::SRA_rr,
            488 => Opcode::SRA_rr_32,
            489 => Opcode::SRL_ri,
            490 => Opcode::SRL_ri_32,
            491 => Opcode::SRL_rr,
            492 => Opcode::SRL_rr_32,
            493 => Opcode::STB,
            494 => Opcode::STB32,
            495 => Opcode::STBREL32,
            496 => Opcode::STB_imm,
            497 => Opcode::STD,
            498 => Opcode::STDREL,
            499 => Opcode::STD_imm,
            500 => Opcode::STH,
            501 => Opcode::STH32,
            502 => Opcode::STHREL32,
            503 => Opcode::STH_imm,
            504 => Opcode::STW,
            505 => Opcode::STW32,
            506 => Opcode::STWREL32,
            507 => Opcode::STW_imm,
            508 => Opcode::SUB_ri,
            509 => Opcode::SUB_ri_32,
            510 => Opcode::SUB_rr,
            511 => Opcode::SUB_rr_32,
            512 => Opcode::XADDD,
            513 => Opcode::XADDW,
            514 => Opcode::XADDW32,
            515 => Opcode::XANDD,
            516 => Opcode::XANDW32,
            517 => Opcode::XCHGD,
            518 => Opcode::XCHGW32,
            519 => Opcode::XFADDD,
            520 => Opcode::XFADDW32,
            521 => Opcode::XFANDD,
            522 => Opcode::XFANDW32,
            523 => Opcode::XFORD,
            524 => Opcode::XFORW32,
            525 => Opcode::XFXORD,
            526 => Opcode::XFXORW32,
            527 => Opcode::XORD,
            528 => Opcode::XORW32,
            529 => Opcode::XOR_ri,
            530 => Opcode::XOR_ri_32,
            531 => Opcode::XOR_rr,
            532 => Opcode::XOR_rr_32,
            533 => Opcode::XXORD,
            534 => Opcode::XXORW32,
            535 => Opcode::INSTRUCTION_LIST_END,
            _ => Opcode::UNKNOWN(value),
        }
    }
}
