class Engine:
    def __init__(self, *args, **kwargs) -> None: ...

class Instruction:
    def __init__(self, *args, **kwargs) -> None: ...
    def to_string(self) -> str: ...
    @property
    def address(self) -> int: ...
    @property
    def is_branch(self) -> bool: ...
    @property
    def is_call(self) -> bool: ...
    @property
    def is_syscall(self) -> bool: ...
    @property
    def is_terminator(self) -> bool: ...
    @property
    def mnemonic(self) -> str: ...
    @property
    def raw(self) -> bytes: ...
    @property
    def size(self) -> int: ...
