name: 'sanitize'
on: workflow_dispatch

jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: compile
        shell: bash
        run: |
          docker run --rm \
           -e BUILD_DIR=/tmp/build_gcc \
           -e SRC_DIR=/src \
           -v $GITHUB_WORKSPACE:/src \
           liefproject/sanity:latest bash /src/scripts/docker/test-gcc
  clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: compile
        shell: bash
        run: |
          docker run --rm \
           -e BUILD_DIR=/tmp/build_clang \
           -e SRC_DIR=/src \
           -v $GITHUB_WORKSPACE:/src \
           liefproject/sanity:latest bash /src/scripts/docker/test-clang
  asan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: compile
        shell: bash
        run: |
          docker run --rm \
           -v $GITHUB_WORKSPACE:/src \
           liefproject/sanity:latest bash /src/scripts/docker/test-asan
